# **Numpy**  
- 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 패키지이다.  
- 많은 머신러닝 알고리즘이 넘파이 기반으로 작성되어 있고, 데이터 입출력도 넘파이 배열 타입을 사용하기 때문에 중요한 패키지이다.

## 개요

In [2]:
import numpy as np

array() 함수  
- 파이썬의 리스트와 같은 다양한 인자를 입력 받아 ndarray로 변환하는 기능을 수행한다.  
- 생성된 ndarray 배열의 shape 변수는 ndarray의 행과 열의 수를 튜플 형태로 가지고 있고, 이를 통해 ndarray 배열의 차원을 알 수 있다.

In [11]:
array1 = np.array([1, 2, 3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)
print()

array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)
print()

array3 = np.array([[1, 2, 3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)
print()

array4 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('array4 type:', type(array4))
print('array4 array 형태:', array4.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)

array2 type: <class 'numpy.ndarray'>
array2 array 형태: (3, 3)

array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)

array4 type: <class 'numpy.ndarray'>
array4 array 형태: (3, 3)


알고리즘 데이터 입출력, 변환시 명확히 1차원 또는 다차원 데이터를 요구하는 경우가 빈번하기 때문에 이 차이를 인지하는 것이 매우 중요하다.

In [14]:
print(f'array1: {array1.ndim}차원, array2: {array2.ndim}차원, array3: {array3.ndim}차원')

array1: 1차원, array2: 2차원, array3: 2차원


## ndarray의 데이터 타입
- ndarray 내의 데이터 값은 숫자, 문자열, 불리언 값 모두 가능하다.
- 하나의 array 내의 데이터 타입은 같은 타입만 가능하다. 숫자형인 int와 float형도 함께 있을 수 없다.

In [16]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


서로 다른 데이터 유형이 섞여있는 리스트를 ndarray로 변경하려고 하면 **데이터 크기가 더 큰 타입**으로 형 변환을 일괄 적용한다.  

str > float > int

In [18]:
list2 = [1, 2, 'test'] # int형과 str형이 섞여있는 리스트
array2 = np.array(list2)
print(array2, array2.dtype) # 유니코드 문자열값으로 데이터 변환
list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype) # float형으로 데이터 변환

['1' '2' 'test'] <U21
[1. 2. 3.] float64


ndarray 내의 데이터 타입 변경도 astype()를 이용하면 가능하다.(메모리 절약)  
가령, int형만으로도 충분한 float 타입의 데이터라면 int형으로 바꿔서 메모리를 절약할 수 있다.

In [27]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
print('array_float1:', array_float1)
array_int2 = array_float.astype('int32')
print('array_int2:', array_int2, array_int2.dtype) # int형으로 변환되면서 소수점이 사라짐

[1. 2. 3.] float64
[1 2 3] int32
array_float1: [1.1 2.1 3.1]
array_int2: [1 2 3] int32


## ndarray 편리하게 생성하기
특정 크기, 차원을 가진 ndarray를 연속값이나 0, 1로 초기화해 쉽게 생성해야할 경우, 또는 테스트용 데이터를 만들거나 대규모 데이터를 일괄적으로 초기화할 때 arange(), zeros(), ones() 함수를 사용한다.

In [30]:
# arange() : 파이썬의 range와 비슷하게 0부터 '인자값-1'의 값을 순차적으로 ndarray의 값으로 변환
sequence_array = np.arange(10)
print(sequence_array)
print(type(sequence_array))
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
int64 (10,)


In [32]:
sequence_array2 = np.arange(3, 10) # 시작값 설정 가능
print(sequence_array2)
print(type(sequence_array2))

[3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [36]:
# dtype default - float64

# zeros() : 튜플형태의 shape 값을 입력하면, 모든 값을 0으로 채운 ndarray 반환
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)
print()

# ones() : 튜플형태의 shape 값을 입력하면, 모든 값을 1으로 채운 ndarray 반환
one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [37]:
# reshape() : ndarray의 차원과 크기 변경
array1 = np.arange(10)
print('array1:\n', array1)
print()

array2 = array1.reshape(2, 5)
print('array2:\n', array2)
print()

array3 = array1.reshape(5, 2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]

array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [38]:
# reshape()는 지정된 사이즈로 변경 불가능할 때 오류 발생
array1.reshape(4, 3)

ValueError: ignored

In [45]:
# reshape()의 인자를 -1로 적용하면, ndarray와 호환되는 새로운 ndarray로 변환
# 차원 상관없이 사이즈에 맞게 적용된다!!
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5)
print('array2 shape:', array2.shape)

array3 = array1.reshape(10, -1) # array3 = array1.reshape(10, 1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (10, 1)


In [50]:
# reshape(-1, 1) : 원본 ndarray가 어떤 형태라도 2차원이고
# 여러 개의 row, 1개의 col을 가진 ndarray로 변환된다.
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d:\n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)


## 넘파이의 ndarray의 데이터셋 선택하기 - 인덱싱(indexing)

### 1. 특정 데이터만 추출

In [53]:
# ndarray 객체에 해당하는 위치의 인덱스 값을 [] 안에 입력
array1 = np.arange(start=1, stop=10)
print('array1:', array1)
value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [55]:
print('맨 뒤의 값:', array1[-1], ', 맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 , 맨 뒤에서 두 번째 값: 8


In [56]:
# 단일 인덱스를 이용해 ndarray 내의 데이터 값 수정 가능
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [63]:
# 2차원 ndarray의 경우 (row, col) 위치로 row와 col의 위치 인덱스를 통해 접근
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d, '\n')

print(f'(row=0, col=0) index 가리키는 값: {array2d[0, 0]}')
print(f'(row=0, col=1) index 가리키는 값: {array2d[0, 1]}')
print(f'(row=1, col=0) index 가리키는 값: {array2d[1, 0]}')
print(f'(row=2, col=2) index 가리키는 값: {array2d[2, 2]}')

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


### 2. 슬라이싱  
- ' : ' 기호를 이용
- ' : ' 기호 앞에 시작 인덱스를 생략하면 자동으로 맨 처음 인덱스로 간주
- ' : ' 기호 뒤에 종료 인덱스를 생략하면 자동으로 맨 마지막 인덱스로 간주
- ' : ' 기호 앞 뒤에 시작/종료 인덱스를 생략하면 자동으로 맨 처음/맨 마지막 인덱스로 간주(전체 선택)

In [65]:
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

array3 = array1[0:3]
print('array3:', array3)
print(type(array3))

array1: [1 2 3 4 5 6 7 8 9]
array3: [1 2 3]
<class 'numpy.ndarray'>


In [66]:
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

array4 = array1[:3]
print('array4:', array4)

array5 = array1[3:]
print('array5:', array5)

array6 = array1[:]
print('array6:', array6)

array1: [1 2 3 4 5 6 7 8 9]
array4: [1 2 3]
array5: [4 5 6 7 8 9]
array6: [1 2 3 4 5 6 7 8 9]


In [76]:
# [row 수, col 수]로 생각하면 쉽다!
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3) # 2차원 ndarray에서 슬라이싱으로 데이터 접근
print('array2d:\n', array2d)

print('array2d[0:2, 0:2]\n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3]\n', array2d[1:3, 0:3])
print('array2d[1:3, :]\n', array2d[1:3, :])
print('array2d[:, :]\n', array2d[:, :])
print('array2d[:2, 1:]\n', array2d[:2, 1:])
print('array2d[:2, 0]\n', array2d[:2, 0])

# [?, 0] 0으로 인덱싱하면 1차원으로 변환?
print(array2d[:, 0], array2d[:, 0].shape)
print(array2d[0, :2], array2d[0, :].shape)

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]
 [[4 5 6]
 [7 8 9]]
array2d[:, :]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]
 [[2 3]
 [5 6]]
array2d[:2, 0]
 [1 4]
[1 4 7] (3,)
[1 2] (3,)


In [78]:
# 2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 인덱스를 반환
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, ', array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) , array2d[1] shape: (3,)


### 팬시 인덱싱
- 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식

In [83]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print('array2d:\n', array2d)

array3 = array2d[[0, 1], 2]
print('array2d[[0, 1], 2] =>', array3.tolist())
print()

array4 = array2d[[0, 1], 0:2]
print('array2d[[0, 1], 0:2] =>', array4.tolist())
print()

array5 = array2d[[0, 1]]
print('array2d[[0, 1]] =>', array5.tolist())

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[[0, 1], 2] => [3, 6]

array2d[[0, 1], 0:2] => [[1, 2], [4, 5]]

array2d[[0, 1]] => [[1, 2, 3], [4, 5, 6]]


### 불린 인덱싱
- 조건 필터링과 검색을 동시에 할 수 있기 때문에 자주 사용되는 인덱싱 방식
- ndarray의 인덱스를 지정하는 [] 내에 조건문을 그대로 기재

In [84]:
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 Boolean indexing 결과값:', array3)

array1d > 5 Boolean indexing 결과값: [6 7 8 9]


In [85]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [86]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('필터링 결과:', array3)

필터링 결과: [6 7 8 9]


In [87]:
indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


## 행렬의 정렬 - sort(), argsort()
- np.sort(): 넘파이에서 sort() 호출 → 원행렬은 그대로 유지한 채, 정렬된 행렬을 반환한다.
- ndarray.sort(): 원행렬 자체를 정렬한 형태로 변환하며 별도로 반환하는 값은 없다.

### sort() 정렬

In [88]:
org_array = np.array([3, 1, 9, 5])
print('원본 행렬:', org_array)

# np.sort() 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)
print()

# ndarray.sort() 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 정렬 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]

org_array.sort() 호출 후 반환된 정렬 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


기본적으로 오름차순으로 행렬 내 원소를 정렬한다.  
→ 내림차순으로 정렬하기 위해서는 [::-1]을 적용하면 된다.

In [89]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [90]:
# 2차원 배열에서 행, 열 정렬
array2d = np.array([[8, 12], [7, 1]])
sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)
sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


### argsort() 정렬

In [91]:
# 정렬 행렬의 인덱스 반환
org_array= np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [92]:
org_array = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [94]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([60, 90, 79, 86, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 3 4 1]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Kate' 'Samuel' 'Mike']


## 선형대수 연산 - 행렬 내적과 전치 행렬 구하기


- 행렬 내적

In [95]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


- 전치 행렬 - 차원 변경

In [96]:
A = np.array([[1, 2], [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
